### ISSUE TITLE
  Cannot read property 'stage' of undefined

### ISSUE THREAD

**Issue by vvondra** [svdgraaf/serverless-plugin-stack-outputs#2]
When running `serverless info outputs`
```
  Type Error ---------------------------------------------
 
  Cannot read property 'stage' of undefined
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: Cannot read property 'stage' of undefined
    at Class.outputStackOutput (node_modules/serverless-plugin-stack-outputs/src/index.js:55:50)
    at BbPromise.reduce (/Users/vojtech/.nvm/versions/node/v8.1.4/lib/node_modules/serverless/lib/classes/PluginManager.js:368:55)
From previous event:
    at PluginManager.invoke (/Users/vojtech/.nvm/versions/node/v8.1.4/lib/node_modules/serverless/lib/classes/PluginManager.js:368:22)
    at PluginManager.run (/Users/vojtech/.nvm/versions/node/v8.1.4/lib/node_modules/serverless/lib/classes/PluginManager.js:399:17)
    at variables.populateService.then (/Users/vojtech/.nvm/versions/node/v8.1.4/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Serverless.run (/Users/vojtech/.nvm/versions/node/v8.1.4/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/Users/vojtech/.nvm/versions/node/v8.1.4/lib/node_modules/serverless/bin/serverless:42:50)
    at <anonymous>
```

**Comment by thbehlau** [comment]
this error still exists! Do we have a fix for  that?
